function Footer(){
    return(
        <>
            <br />
            <div className="mx-4">
                <h2 className="font-semibold">Superior online shopping in the UAE</h2>
                <p className="font-light text-[black]">
                    As the leading destination for online shopping in the UAE, noon has everything you need under one roof. Whether you’re shopping for the latest electronic products, fashion, homeware, products for kids and babies, books and stationery, sports and health essentials, beauty products, or groceries, we have millions of products in the noon UAE store. As a customer-centric online store, we make it easier to buy online with flexible payment plans that help you save, along with regular sales across our extensive product range, gift cards, wishlists, our exclusive Mashreq VIP card, our easy-to-use shopping app, and so much more. <br /><br />
                    At noon, we work hard to deliver the very best experience for our customers. We deliver to Dubai, Abu Dhabi and all other cities in the UAE. As a superstore with multiple departments and exceptional customer service, we offer so much more than your average online shop. We go above and beyond to make your shopping experience as stress-free as possible, with products that offer long-term quality. Save time and effort, and enjoy one-stop shopping from the comfort of your home. Shop online and get free shipping on orders over a set amount.
                </p>
                <br />
                <h2 className="font-semibold">Shop the best products & brands at noon UAE</h2> 
                <p className="font-light text-[black]">
                You’ll find a massive variety of products from top brands at noon UAE. Our electronics department has the latest mobile phones, along with tablets, mobile accessories, laptops, wearable technology such as smartwatches and other wearable devices, headphones (in-ear, wireless and noise-cancelling), audiovisual gear, a selection of cameras, televisions, video game consoles such as PC and Xbox controllers, and video games. We have products from Samsung, Xiaomi, Sony, HP, Dell, Huawei, Lenovo, Apple, and many other leading tech brands. <br /> <br />
                Looking for the best mobiles in UAE? At noon, we have a hand-picked collection of best-selling phones to suit your needs. Our range of Apple phones includes models such as the iPhone 11, iPhone 12, iPhone 13, iPhone 14, and the iPhone 15. For those wanting added features, our range also includes the iPhone 11 Pro, iPhone 11 Pro Max, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 13 Pro, iPhone 13 Pro Max, iPhone 14 Plus, iPhone 14 Pro,iPhone 14 Pro Max, iPhone 15 Pro, and iPhone 15 Pro Max. Top Android phones include the Galaxy 22 Ultra, as well as the Galaxy 23 and the Honor X9a. <br /> <br />
                In our home and kitchen department, you’ll find a massive variety of products from Home Box, Fashionhome, Pan Emirates and other brands. We have a large variety of home appliances in the store, from large appliances such as fridges and washing machines to small appliances such as air fryers, coffee makers, irons, heaters, and more. Our furniture range includes beds, sofas and couches, chairs, tables, and other furniture. The home and kitchen department includes everyday essentials such as food storage, cookware, bedding, home improvement supplies and tools, home decor, lighting, and many other must-haves for your home. Our automotive department has everything you need to keep your car maintained. <br /> <br />
                Our UAE beauty store features a wide range of products - hair care and personal care products, fragrances and perfumes, cosmetics, skincare products, grooming products, bath and body products, and more. This range includes products from leading brands, including Calvin Klein, Roberto Cavalli, L'Oreal Paris and many others. <br /> <br />
                Shop fashion online to find a wide range of clothing, shoes and accessories for men, women and kids. Our UAE women’s clothing store includes apparel from top brands such as Tommy Hilfiger, Adidas, Vero Moda, Sketchers and others. Our women’s fashion department includes sportswear, dresses, traditional and ethnic clothing, dresses, tops, shoes, handbags, accessories, and everything else you need to look your best. Our UAE men’s clothing store features fashion, accessories, and footwear from Nike, Puma, Adidas, Tommy Hilfiger and other leading fashion brands. Our accessories range includes watches, eyewear, handbags, and other style essentials. You will find plenty of clothing, accessories and shoes for boys and girls of all ages in our UAE kids’ clothing store. Shop clothes online to view our full collections. <br /> <br />
                For little ones, we have a variety of baby and kids products in the noon UAE shop, from leading brands such as Intex, Lego, Barbie, Nerf and many others. Shop our range of toys for kids of every age to find fun, interactive games, card games, outdoor play equipment, scooters, and other things to keep your child busy. Our baby product selection features everything from diapers to baby transport, nursing and feeding products, baby toys, and more. <br /><br />
                Get active with our huge selection of sporting and outdoor products from Muscletech, Skyland, Sparnod Fitness, Everlast and other brands. This department has everything from fitness and training equipment, sports and health nutrition, cycling essentials, and specialised sporting equipment for boxing, yoga, swimming, and other sports. <br /><br />
                Online food shopping in UAE is simple, thanks to noon Grocery - the fastest, simplest way to get great deals on food essentials. From fresh food to pantry items, cooking essentials, household items, cleaning and laundry products, and more, we offer fast delivery to your door. We have products from our in-house noon brand as well as quality imported brands. <br /><br />
                </p>
                <h2 className="font-semibold">Hassle-free UAE online shopping</h2>
                <p className="font-light text-[black]">
                When you buy online at noon, you will always have peace of mind knowing that you are getting the best level of service. We take the hassle out of online shopping in Abu Dhabi and Dubai, with a number of features and flexible payment plans that make shopping simpler, faster, and better. Our Buy Now, Pay Later plans include Tabby, with orders split over 4 payments, and Tamara, with orders split over 3 payments. Both plans are interest-free. We accept credit cards and debit cards from Emirates NBD, FAB bank, Mashreq bank, ADCB, and ADIB, and cash on delivery. For even more convenience, we have a No-Cost EMI. We have a 15-day return policy that takes even more stress out of shopping. <br /><br />
                Set up a wishlist quickly and easily, and share your list with friends and family. Our website is easy to use. Shop by department or sub-category to find what you need. You can also use our advanced search features to filter products according to price and other criteria. Get the same shopping experience and download the noon app - available on App Store and Play Store. This app has all the features of the noon online store, along with exclusive benefits, regular deals, and more. <br /><br />
                However you choose to shop online in Dubai, Abu Dhabi and other cities across the UAE, noon makes shopping easy. Say goodbye to crowded malls, long lines and stressful in-store shopping for good. Get all the benefits of shopping from home when you shop online in Abu Dhabi and Dubai. To get started, sign up for your account, set your delivery address, and then choose your payment option. Browse our departments and add products to your cart. Once you’re finished shopping, complete the checkout process. We’ll take over from there, preparing your order for delivery. Your order will then be shipped straight to your door. <br /><br />
                Sign up for your account at the noon UAE online shop now to start shopping. Happy shopping!
                </p>
            </div>
        </>
    )
}
export default Footer